stages: 
  - build
  - test

jobs: 
  build_and_lint:
    stage: build
    image: node:16-alpine
    script: 
      - yarn install --frozen-lockfile
      - yarn eslint .
  
  test: 
    stage: test
    image: node:16-alpine
    script:
      - cd server
      - yarn install
      - yarn test
